services:
  db:
    container_name: barbershop-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: "barbershop"
      POSTGRES_USER: "barberuser"
      POSTGRES_PASSWORD: "barberpass"
    ports:
      - "5433:5432"
    volumes:
      - barbershop-postgres-data:/var/lib/postgresql/data

volumes:
  barbershop-postgres-data: